/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Doctor;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Patient.Medicine;
import Business.Patient.Patient;
import Business.WorkQueue.BookAppointment;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Likitha G
 */
public class PrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescriptionJPanel
     */
   JPanel userProcessContainer;
    EcoSystem system;
    BookAppointment pa;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public PrescriptionJPanel(JPanel userProcessContainer,EcoSystem system,BookAppointment pa) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.pa = pa;
        
        dName.setText(pa.getSender().getEmployee().getName());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dName = new javax.swing.JTextField();
        dmed = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dmed2 = new javax.swing.JTextField();
        dmed3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dcomments = new javax.swing.JTextField();
        enterpriseLabel = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Patient Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 94, -1, -1));

        jLabel3.setText("Medicine 1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 141, -1, -1));
        add(dName, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 84, 150, -1));
        add(dmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 131, 150, -1));

        jButton1.setBackground(new java.awt.Color(24, 31, 46));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add presecription");
        jButton1.setPreferredSize(new java.awt.Dimension(156, 43));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 315, -1, -1));

        jLabel4.setText("Medicine 2");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 180, -1, -1));

        jLabel5.setText("Medicine 3");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 227, -1, -1));
        add(dmed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 175, 150, -1));
        add(dmed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 222, 150, -1));

        jLabel6.setText("Comments");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 265, -1, -1));
        add(dcomments, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 260, 150, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Add Prescription");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 180, 30));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/p10.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 420));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (dmed.getText().isEmpty() && dmed2.getText().isEmpty() && dmed2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter atleast one medicine");
            return;
        } else {
            if ((!dmed.getText().matches("[a-zA-Z_]+")) &&(!dmed3.getText().matches("[a-zA-Z_]+"))&& (!dmed2.getText().matches("[a-zA-Z_]+"))) {
                JOptionPane.showMessageDialog(this, "Enter proper medicine name");
                dmed.setText("");
                dmed2.setText("");
                dmed3.setText("");
                return;
            }
            //            }
        //            else if(!dmed2.getText().matches("[a-zA-Z_]+")) {
            //                JOptionPane.showMessageDialog(this, "Enter proper medicine name");
            //                dmed2.setText("");
            //                return;
            //            } else if(!dmed3.getText().matches("[a-zA-Z_]+")) {
            //                JOptionPane.showMessageDialog(this, "Enter proper medicine name");
            //                dmed3.setText("");
            //                return;
            //            }
        else{}
        ArrayList<String> med = new ArrayList<>();
        if(!dmed.getText().isEmpty()) {String med1 = dmed.getText(); med.add(med1);}
        if(!dmed2.getText().isEmpty()) {String med2 = dmed2.getText();med.add(med2);}
        if(!dmed3.getText().isEmpty()) {String med3 = dmed3.getText();med.add(med3);}
        //
        //        med.add(med1);
        //        med.add(med2);
        //        med.add(med3);
        Medicine md = new Medicine();
        md.setMedicines(med);

        pa.setMeds(md);
        pa.setComments(dcomments.getText());
        System.out.println("bbb  " +pa.getMeds().getMedicines().get(0));
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        //
        //        Component[] comps = this.userProcessContainer.getComponents();
        //        for(Component comp : comps){
            //            if(comp instanceof SystemAdminWorkAreaJPanel){
                //                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                //                systemAdminWorkAreaJPanel.populateTree();
                //            }
            //        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dName;
    private javax.swing.JTextField dcomments;
    private javax.swing.JTextField dmed;
    private javax.swing.JTextField dmed2;
    private javax.swing.JTextField dmed3;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
